version: "3.4"
services:
  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - '6379:6379'
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - '127.0.0.1:8001:8001'
    volumes:
      - redis_insight_volume_data:/db
  brushserver:
    build: ./server
    container_name: brushserver
    restart: always
    ports:
      - '127.0.0.1:8002:8002'
  brushclient:
    build: ./client
    container_name: brushclient
    restart: always
    ports:
      - '127.0.0.1:8003:8003'

volumes:
  redis_volume_data:
  redis_insight_volume_data:
  brushserver:
  brushclient:
