version: "3.4"
services:
  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - '127.0.0.1:6379:6379/tcp'
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - '127.0.0.1:8001:8001'
    volumes:
      - redis_insight_volume_data:/db


volumes:
  redis_volume_data:
  redis_insight_volume_data:
